FROM ${DOCKER_ORG_NAME}/${PKG_NAME}-srpm-deps

MAINTAINER "Jiao Lin <jiao.lin@gmail.com>"

RUN dpkg -i ${GITHUB_URL}/releases/download/v${VERSION}/${PKG_NAME}-${VERSION}-${CPACK_PACKAGE_RELEASE}.x86_64.deb
